project:
  type: website

website:
  title: "SPI Québec"
  image: assets/img/logo.png
  navbar:
    # background: light
    logo: assets/img/logo.png
    logo-alt: "BdQc logo."
    title: false
    collapse-below: lg
    left:
      - text: "À propos"
        href: about.qmd
      - text: "Histoire de biodiversité"
        href: index.qmd
      - text: "SPI"
        href: SPI.qmd
          
    tools:
      - icon: github
        href: https://github.com/ReseauBiodiversiteQuebec/SPI
        text: SPI GitHub        

  sidebar:
    - id: "Histoire de biodiversité"
    - id: SPI
      collapse-level: 1
      contents:
        - section: "SPI"
          href: SPI.qmd
          contents:
            - section: "Aires de répartition"
              href: results/section_ranges/description.md
              contents:
                - docs/results_ranges.qmd
            - section: "Occurences"
              href: results/section_occurences/description.md
              contents:
                - docs/results_occurences.qmd
            - section: "Cartes de Vincent Bellavance"
              href: results/section_bellavance/description.md
              contents:
                - docs/results_bellavance.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



