name: Update Content

on:
  push:
    branches:
      - section_occurences # Trigger the workflow on pushes to section branches
      - section_ranges
      - section_bellavance
      - quarto-web

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Copy Content to Master Branch (section_occurences)
        run: |
          SECTION_BRANCH='section_occurences'
          SECTION_CONTENT_PATH='results'
          mkdir -p $SECTION_CONTENT_PATH/$SECTION_BRANCH/
          cp -r $SECTION_BRANCH/$SECTION_CONTENT_PATH/* $SECTION_CONTENT_PATH/$SECTION_BRANCH/
          cp -r $SECTION_BRANCH/README.md $SECTION_CONTENT_PATH/$SECTION_BRANCH/description.md
          git add .
          git commit -m "Update content from $SECTION_BRANCH"
          git push origin quarto-web
        env:
          SECTION_BRANCH: ${{ github.event.ref }}

      - name: Copy Content to Master Branch (section_ranges)
        run: |
          SECTION_BRANCH='section_ranges'
          SECTION_CONTENT_PATH='results'
          mkdir -p $SECTION_CONTENT_PATH/$SECTION_BRANCH/
          cp -r $SECTION_BRANCH/$SECTION_CONTENT_PATH/* $SECTION_CONTENT_PATH/$SECTION_BRANCH/
          cp -r $SECTION_BRANCH/README.md $SECTION_CONTENT_PATH/$SECTION_BRANCH/description.md
          git add .
          git commit -m "Update content from $SECTION_BRANCH"
          git push origin quarto-web
        env:
          SECTION_BRANCH: ${{ github.event.ref }}

      - name: Copy Content to Master Branch (section_bellavance)
        run: |
          SECTION_BRANCH='section_bellavance'
          SECTION_CONTENT_PATH='results'
          mkdir -p $SECTION_CONTENT_PATH/$SECTION_BRANCH/
          cp -r $SECTION_BRANCH/$SECTION_CONTENT_PATH/* $SECTION_CONTENT_PATH/$SECTION_BRANCH/
          cp -r $SECTION_BRANCH/README.md $SECTION_CONTENT_PATH/$SECTION_BRANCH/description.md
          git add .
          git commit -m "Update content from $SECTION_BRANCH"
          git push origin quarto-web
        env:
          SECTION_BRANCH: ${{ github.event.ref }}

